### PR TITLE
Feature/batching

### PR DESCRIPTION
**Pull request by joe-keen**

### CODE REVIEW

**Comment by oneilcin** [comment]
It looks like the code sends either a list of events or a single event to kafka for the events-engine.  I believe the events-engine supports a single event, so the parsing of events in the engine may need to change if it could receive a list of events.

**Comment by oneilcin** [comment]
The code looks good here.

**Comment by joe-keen** [comment]
The cool part about the Kafka batching is that writing a list of events or a single event has no effect on the read side.  The reader still sees just single events even when the writer sends batches into Kafka.

**Comment by oneilcin** [comment]
cool - merge it!

**Pull request merged**
